apiVersion: choreo.kform.dev/v1alpha1
kind: Library
metadata:
  creationTimestamp: "2024-09-08T13:10:06Z"
  managedFields:
  - apiVersion: choreo.kform.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:code: {}
        f:type: {}
      f:status: {}
    manager: inputfileloader
    operation: Apply
    time: "2024-09-08T13:10:06Z"
  name: device.network.kubenet.dev.bgpneighbors.star
  resourceVersion: "0"
  uid: b3ae35c4-9f5f-412b-8436-2be77936e302
spec:
  code: |-
    def getSpec(self):
      return self.get("spec", {})

    def getPartition(self):
      spec = getSpec(self)
      return spec.get("partition", "")

    def getBGPNeighbor(name, namespace, spec):
      return {
        "apiVersion": "device.network.kubenet.dev/v1alpha1",
        "kind": "BGPNeighbor",
        "metadata": {
            "name": name,
            "namespace": namespace
        },
        "spec": spec,
      }
  type: starlark
status: {}
