apiVersion: choreo.kform.dev/v1alpha1
kind: Library
metadata:
  creationTimestamp: "2024-09-08T13:10:06Z"
  managedFields:
  - apiVersion: choreo.kform.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:code: {}
        f:type: {}
      f:status: {}
    manager: inputfileloader
    operation: Apply
    time: "2024-09-08T13:10:06Z"
  name: ipam.be.kuid.dev.ipclaims.star
  resourceVersion: "0"
  uid: bae51594-031a-4bef-8486-4927407e9ee7
spec:
  code: "def getIPClaimedAddress(name, namespace):\n  resource = get_resource(\"ipam.be.kuid.dev/v1alpha1\",
    \"IPClaim\")\n  rsp = client_get(name, namespace, resource[\"resource\"])\n  if
    rsp[\"error\"] != None:\n    return None, \"ipclaim \" + name + \" err: \" + rsp[\"error\"]\n
    \ \n  if is_conditionready(rsp[\"resource\"], \"Ready\") != True:\n    return
    None, \"ipclaim \" + name + \" not ready\"\n  status = rsp[\"resource\"].get(\"status\",
    {})\n  address = status.get(\"address\", \"\")\n  if address == \"\":\n    return
    None, \"ipclaim \" + name + \" no address in ip claim\"\n  return address, None\n\ndef
    getIPClaim(name, namespace, spec):\n  return {\n    \"apiVersion\": \"ipam.be.kuid.dev/v1alpha1\",\n
    \   \"kind\": \"IPClaim\",\n    \"metadata\": {\n        \"name\": name,\n        \"namespace\":
    namespace\n    },\n    \"spec\": spec,\n  }"
  type: starlark
status: {}
