apiVersion: core.network.kubenet.dev/v1alpha1
kind: NetworkDesign
metadata:
  creationTimestamp: "2024-09-08T13:10:06Z"
  managedFields:
  - apiVersion: core.network.kubenet.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:encapsulation:
          f:vxlan: {}
        f:interfaces:
          f:loopback:
            f:addressing: {}
            f:prefixes: {}
          f:underlay:
            f:addressing: {}
            f:prefixes: {}
        f:protocols:
          f:bgpEVPN: {}
          f:ebgp:
            f:asPool: {}
            f:bfd: {}
          f:ibgp:
            f:as: {}
            f:localAS: {}
            f:routeReflectors: {}
    manager: inputfileloader
    operation: Apply
    time: "2024-09-08T13:10:06Z"
  - apiVersion: core.network.kubenet.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"Ready"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: core.network.kubenet.dev.networkdesigns.networkdesign
    operation: Apply
    time: "2024-09-08T13:21:36Z"
  name: kubenet
  namespace: default
  resourceVersion: "1"
  uid: 962f2030-c5e1-4ee7-b4d8-e88393938271
spec:
  encapsulation:
    vxlan: {}
  interfaces:
    loopback:
      addressing: dualstack
      prefixes:
      - prefix: 10.0.0.0/16
      - prefix: 1000::/64
    underlay:
      addressing: dualstack
      prefixes:
      - prefix: 192.0.0.0/16
      - prefix: 1192::/56
  protocols:
    bgpEVPN: {}
    ebgp:
      asPool: 65000-65100
      bfd: true
    ibgp:
      as: 65535
      localAS: true
      routeReflectors:
      - topo3nodesrl.default.core01.ipv4
status:
  conditions:
  - lastTransitionTime: "2024-09-08T13:21:36Z"
    message: ""
    reason: Ready
    status: "True"
    type: Ready
