apiVersion: choreo.kform.dev/v1alpha1
kind: Reconciler
# name can be inferred from the filename or from the for resource
spec: 
  for: 
    group: core.network.kubenet.dev
    version: v1alpha1
    kind: NetworkDesign
    selector: {}
  owns:
  - group: ipam.be.kuid.dev
    version: v1alpha1
    kind: IPClaim
  - group: as.be.kuid.dev
    version: v1alpha1
    kind: ASClaim
