apiVersion: choreo.kform.dev/v1alpha1
kind: Reconciler
# name can be inferred from the filename or from the for resource
spec: 
  for: 
    group: device.network.kubenet.dev
    version: v1alpha1
    kind: NetworkInstance
    selector: {}
  watches:
  - group: device.network.kubenet.dev
    version: v1alpha1
    kind: SubInterface
    selector:
      match:
        spec.partition: spec.partition
        spec.region: spec.region
        spec.site: spec.site
        spec.node: spec.node

