apiVersion: choreo.kform.dev/v1alpha1
kind: Reconciler
# name can be inferred from the filename or from the for resource
spec: 
  for: 
    group: infra.kuid.dev
    version: v1alpha1
    kind: Link
    selector:
      match:
        spec.internal: "true" # bool need to be presented as string
  owns:
  - group: ipam.be.kuid.dev
    version: v1alpha1
    kind: IPClaim
  watches:
  - group: core.network.kubenet.dev
    version: v1alpha1
    kind: NetworkDesign
    selector:
      match:
        metadata.name: spec.partition
        status.conditions.exists(c, c.type == 'Ready' && c.status == 'True'): "true"
        
