apiVersion: device.network.kubenet.dev/v1alpha1
kind: BGP
metadata:
  creationTimestamp: "2024-09-08T13:21:37Z"
  generation: 3
  managedFields:
  - apiVersion: device.network.kubenet.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          k:{"uid":"7655f1b7-4c09-471f-b89b-f3f865f96cab"}: {}
      f:spec:
        f:addressFamilies:
          k:{"name":"bgpEVPN"}:
            .: {}
            f:name: {}
          k:{"name":"ipv4Unicast"}:
            .: {}
            f:name: {}
          k:{"name":"ipv6Unicast"}:
            .: {}
            f:name: {}
        f:as: {}
        f:node: {}
        f:partition: {}
        f:peerGroups:
          k:{"name":"overlay"}:
            .: {}
            f:addressFamilies: {}
            f:name: {}
          k:{"name":"underlay"}:
            .: {}
            f:addressFamilies: {}
            f:name: {}
        f:region: {}
        f:routerID: {}
        f:site: {}
    manager: infra.kuid.dev.nodes.bgp
    operation: Apply
    time: "2024-09-09T14:01:04Z"
  name: kubenet.region1.us-east.node1
  namespace: default
  ownerReferences:
  - apiVersion: infra.kuid.dev/v1alpha1
    controller: true
    kind: Node
    name: kubenet.region1.us-east.node1
    uid: 7655f1b7-4c09-471f-b89b-f3f865f96cab
  resourceVersion: "3"
  uid: cb62b833-ddcb-4d6c-aef0-31681333e95c
spec:
  addressFamilies:
  - name: ipv4Unicast
  - name: ipv6Unicast
  - name: bgpEVPN
  as: 65001
  node: node1
  partition: kubenet
  peerGroups:
  - addressFamilies:
    - name: ipv4Unicast
    - name: ipv6Unicast
    name: underlay
  - addressFamilies:
    - name: bgpEVPN
    name: overlay
  region: region1
  routerID: 10.0.0.0
  site: us-east
