apiVersion: topo.kubenet.dev/v1alpha1
kind: Topology
metadata:
  creationTimestamp: "2024-09-08T13:10:06Z"
  managedFields:
  - apiVersion: topo.kubenet.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:defaults:
          f:platformType: {}
          f:provider: {}
          f:region: {}
          f:site: {}
        f:links: {}
        f:nodes: {}
    manager: inputfileloader
    operation: Apply
    time: "2024-09-08T13:10:06Z"
  - apiVersion: topo.kubenet.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"IndexReady"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: topo.kubenet.dev.topologies.index
    operation: Apply
    time: "2024-09-08T13:21:36Z"
  - apiVersion: topo.kubenet.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"LinkNodeReady"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: topo.kubenet.dev.topologies.nodelink
    operation: Apply
    time: "2024-09-08T13:21:36Z"
  name: kubenet
  namespace: default
  resourceVersion: "2"
  uid: fe54f007-12a1-4a44-8d7a-5764db23732a
spec:
  defaults:
    platformType: ixrd3
    provider: srlinux.nokia.com
    region: region1
    site: us-east
  links:
  - endpoints:
    - adaptor: sfp
      endpoint: 1
      node: node1
      port: 1
    - adaptor: sfp
      endpoint: 1
      node: node2
      port: 1
  nodes:
  - name: node1
  - name: node2
status:
  conditions:
  - lastTransitionTime: "2024-09-08T13:21:36Z"
    message: ""
    reason: Ready
    status: "True"
    type: LinkNodeReady
  - lastTransitionTime: "2024-09-08T13:21:36Z"
    message: ""
    reason: Ready
    status: "True"
    type: IndexReady
