apiVersion: infra.kuid.dev/v1alpha1
kind: Adaptor
metadata:
  creationTimestamp: "2024-09-09T06:12:13Z"
  managedFields:
  - apiVersion: infra.kuid.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          k:{"uid":"97e77042-eb65-4b8a-afe7-bd1c97889bdd"}: {}
      f:spec:
        f:adaptor: {}
        f:node: {}
        f:partition: {}
        f:port: {}
        f:region: {}
        f:site: {}
    manager: infra.kuid.dev.nodes.srlinux
    operation: Apply
    time: "2024-09-09T06:12:13Z"
  name: kubenet.region1.us-east.node1.26.xfp
  namespace: default
  ownerReferences:
  - apiVersion: infra.kuid.dev/v1alpha1
    controller: true
    kind: Node
    name: kubenet.region1.us-east.node1
    uid: 97e77042-eb65-4b8a-afe7-bd1c97889bdd
  resourceVersion: "0"
  uid: 5840104d-34e4-4150-903a-1c1d51707442
spec:
  adaptor: xfp
  node: node1
  partition: kubenet
  port: 26
  region: region1
  site: us-east
