apiVersion: ipam.be.kuid.dev/v1alpha1
kind: IPClaim
metadata:
  creationTimestamp: "2024-09-08T13:21:37Z"
  managedFields:
  - apiVersion: ipam.be.kuid.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          k:{"uid":"64d72a34-f000-4d99-8c1b-bef2cf7cf37b"}: {}
      f:spec:
        f:addressFamily: {}
        f:createPrefix: {}
        f:index: {}
        f:prefixLength: {}
        f:prefixType: {}
        f:selector: {}
    manager: infra.kuid.dev.links.link-internal-id
    operation: Apply
    time: "2024-09-08T13:21:37Z"
  name: kubenet.region1.us-east.node1.1.1.node2.1.1.ipv6
  namespace: default
  ownerReferences:
  - apiVersion: infra.kuid.dev/v1alpha1
    controller: true
    kind: Link
    name: kubenet.region1.us-east.node1.1.1.node2.1.1
    uid: 64d72a34-f000-4d99-8c1b-bef2cf7cf37b
  resourceVersion: "0"
  uid: 1d66be52-cf8e-4ca8-854f-109ee594b425
spec:
  addressFamily: ipv6
  createPrefix: true
  index: kubenet.default
  prefixLength: 64
  prefixType: network
  selector:
    matchLabels:
      infra.kuid.dev/purpose: underlay
      ipam.be.kuid.dev/address-family: ipv6
status:
  conditions:
  - lastTransitionTime: "2024-09-08T13:21:37Z"
    message: ""
    reason: Ready
    status: "True"
    type: Ready
  prefix: 1192:0:0:1::/64
