apiVersion: choreo.kform.dev/v1alpha1
kind: Library
metadata:
  creationTimestamp: "2024-09-08T14:44:23Z"
  managedFields:
  - apiVersion: choreo.kform.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:code: {}
        f:type: {}
      f:status: {}
    manager: inputfileloader
    operation: Apply
    time: "2024-09-08T14:44:23Z"
  name: infra.kuid.dev.ports.star
  resourceVersion: "0"
  uid: 37ea6a9a-ef43-431a-a415-e3ecfef61fd6
spec:
  code: |-
    def getPort(name, namespace, spec):
      return {
        "apiVersion": "infra.kuid.dev/v1alpha1",
        "kind": "Port",
        "metadata": {
            "name": name,
            "namespace": namespace,
        },
        "spec": spec,
      }
  type: starlark
status: {}
