apiVersion: config.pkg.pkgserver.dev/v1alpha1
kind: Repository
metadata:
  name: repo-target
spec:
  type: git
  deployment: true
  git:
    url: https://github.com/kubenet-dev/demo.git
    credentials: git-pat
