apiVersion: infra.kuid.dev/v1alpha1
kind: Port
metadata:
  creationTimestamp: "2024-09-08T13:21:36Z"
  managedFields:
  - apiVersion: infra.kuid.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          k:{"uid":"ecf6be81-c341-4f99-8662-af87724203fe"}: {}
      f:spec:
        f:node: {}
        f:partition: {}
        f:port: {}
        f:region: {}
        f:site: {}
    manager: infra.kuid.dev.nodes.srlinux
    operation: Apply
    time: "2024-09-08T13:21:36Z"
  name: kubenet.region1.us-east.node2.16
  namespace: default
  ownerReferences:
  - apiVersion: infra.kuid.dev/v1alpha1
    controller: true
    kind: Node
    name: kubenet.region1.us-east.node2
    uid: ecf6be81-c341-4f99-8662-af87724203fe
  resourceVersion: "0"
  uid: 227cc236-5b2b-423d-9c40-d82c6e6df574
spec:
  node: node2
  partition: kubenet
  port: 16
  region: region1
  site: us-east
