apiVersion: ipam.be.kuid.dev/v1alpha1
kind: IPEntry
metadata:
  creationTimestamp: "2024-09-08T13:21:36Z"
  managedFields:
  - apiVersion: ipam.be.kuid.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          k:{"uid":"5e55589a-f976-444c-b678-029118d951b9"}: {}
      f:spec:
        f:addressFamily: {}
        f:claimType: {}
        f:index: {}
        f:prefix: {}
        f:prefixType: {}
      f:status: {}
    manager: backend
    operation: Apply
    time: "2024-09-08T13:21:36Z"
  name: kubenet.default.192.0.0.2-31
  namespace: default
  ownerReferences:
  - apiVersion: ipam.be.kuid.dev/v1alpha1
    kind: IPClaim
    name: kubenet.region1.us-east.node1.1.1.node2.1.1.ipv4
    uid: 5e55589a-f976-444c-b678-029118d951b9
  resourceVersion: "0"
  uid: 65c6a030-14b2-4fbe-9f02-cb7885f0f72b
spec:
  addressFamily: ipv4
  claimType: dynamicPrefix
  index: kubenet.default
  prefix: 192.0.0.2/31
  prefixType: network
status: {}
