apiVersion: ipam.be.kuid.dev/v1alpha1
kind: IPEntry
metadata:
  creationTimestamp: "2024-09-08T13:10:06Z"
  managedFields:
  - apiVersion: ipam.be.kuid.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          k:{"uid":"6d92b49d-fb4a-452d-b6ed-e2fcf31011be"}: {}
      f:spec:
        f:addressFamily: {}
        f:claimType: {}
        f:index: {}
        f:prefix: {}
        f:prefixType: {}
      f:status: {}
    manager: backend
    operation: Apply
    time: "2024-09-08T13:10:06Z"
  name: kubenet.default.1000---32
  namespace: default
  ownerReferences:
  - apiVersion: ipam.be.kuid.dev/v1alpha1
    kind: IPIndex
    name: kubenet.default
    uid: 6d92b49d-fb4a-452d-b6ed-e2fcf31011be
  resourceVersion: "0"
  uid: 145a6775-5c36-42e9-95a0-8e8c3dbb0138
spec:
  addressFamily: ipv6
  claimType: staticPrefix
  index: kubenet.default
  prefix: 1000::/32
  prefixType: aggregate
status: {}
