apiVersion: infra.kuid.dev/v1alpha1
kind: Node
metadata:
  creationTimestamp: "2024-09-08T13:21:36Z"
  managedFields:
  - apiVersion: infra.kuid.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"RoutingPolicyReady"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: infra.kuid.dev.nodes.routingpolicy
    operation: Apply
    time: "2024-09-08T13:21:36Z"
  - apiVersion: infra.kuid.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"VendorReady"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: infra.kuid.dev.nodes.srlinux
    operation: Apply
    time: "2024-09-08T13:21:36Z"
  - apiVersion: infra.kuid.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          k:{"uid":"fe54f007-12a1-4a44-8d7a-5764db23732a"}: {}
      f:spec:
        f:node: {}
        f:partition: {}
        f:platformType: {}
        f:provider: {}
        f:region: {}
        f:site: {}
    manager: topo.kubenet.dev.topologies.nodelink
    operation: Apply
    time: "2024-09-08T13:21:36Z"
  - apiVersion: infra.kuid.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"BGPReady"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: infra.kuid.dev.nodes.bgp
    operation: Apply
    time: "2024-09-08T13:21:37Z"
  - apiVersion: infra.kuid.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"IPClaimReady"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: infra.kuid.dev.nodes.id
    operation: Apply
    time: "2024-09-08T13:21:37Z"
  - apiVersion: infra.kuid.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"InterfaceReady"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: infra.kuid.dev.nodes.if-si-ni
    operation: Apply
    time: "2024-09-08T13:21:37Z"
  name: kubenet.region1.us-east.node1
  namespace: default
  ownerReferences:
  - apiVersion: topo.kubenet.dev/v1alpha1
    controller: true
    kind: Topology
    name: kubenet
    uid: fe54f007-12a1-4a44-8d7a-5764db23732a
  resourceVersion: "7"
  uid: 7655f1b7-4c09-471f-b89b-f3f865f96cab
spec:
  node: node1
  partition: kubenet
  platformType: ixrd3
  provider: srlinux.nokia.com
  region: region1
  site: us-east
status:
  conditions:
  - lastTransitionTime: "2024-09-08T13:21:37Z"
    message: ""
    reason: Ready
    status: "True"
    type: IPClaimReady
  - lastTransitionTime: "2024-09-08T13:21:36Z"
    message: ""
    reason: Ready
    status: "True"
    type: RoutingPolicyReady
  - lastTransitionTime: "2024-09-08T13:21:36Z"
    message: ""
    reason: Ready
    status: "True"
    type: VendorReady
  - lastTransitionTime: "2024-09-08T13:21:37Z"
    message: ""
    reason: Ready
    status: "True"
    type: BGPReady
  - lastTransitionTime: "2024-09-08T13:21:37Z"
    message: ""
    reason: Ready
    status: "True"
    type: InterfaceReady
