apiVersion: infra.kuid.dev/v1alpha1
kind: Link
metadata:
  creationTimestamp: "2024-09-09T06:12:13Z"
  managedFields:
  - apiVersion: infra.kuid.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"Ready"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: infra.kuid.dev.links.link-ep
    operation: Apply
    time: "2024-09-09T06:12:13Z"
  - apiVersion: infra.kuid.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          k:{"uid":"80b7d6fc-3364-4c6f-83a6-808fb43755f6"}: {}
      f:spec:
        f:endpoints: {}
        f:internal: {}
    manager: topo.kubenet.dev.topology.nodelink
    operation: Apply
    time: "2024-09-09T06:12:13Z"
  name: kubenet.region1.us-east.node1.1.1.node2.1.1
  namespace: default
  ownerReferences:
  - apiVersion: topo.kubenet.dev/v1alpha1
    controller: true
    kind: Topology
    name: kubenet
    uid: 80b7d6fc-3364-4c6f-83a6-808fb43755f6
  resourceVersion: "2"
  uid: f528a36b-a4ff-4c88-a3ac-c455285fe4c4
spec:
  endpoints:
  - adaptor: sfp
    endpoint: 1
    module: 0
    node: node1
    partition: kubenet
    port: 1
    region: region1
    site: us-east
  - adaptor: sfp
    endpoint: 1
    module: 0
    node: node2
    partition: kubenet
    port: 1
    region: region1
    site: us-east
  internal: true
status:
  conditions:
  - lastTransitionTime: "2024-09-09T06:12:13Z"
    message: ""
    reason: Ready
    status: "True"
    type: Ready
