apiVersion: choreo.kform.dev/v1alpha1
kind: ConfigGenerator
# name can be inferred from the filename or from the for resource
spec: 
  providerSelector:
    group: infra.kuid.dev
    version: v1alpha1
    kind: Node
    match:
      spec.partition: spec.partition
      spec.region: spec.region
      spec.site: spec.site
      spec.node: spec.node
    fieldPath: spec.provider
  dir: configgenerator