apiVersion: infra.kuid.dev/v1alpha1
kind: Link
metadata:
  creationTimestamp: "2024-09-08T13:21:36Z"
  managedFields:
  - apiVersion: infra.kuid.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"Ready"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: infra.kuid.dev.links.link-ep
    operation: Apply
    time: "2024-09-08T13:21:36Z"
  - apiVersion: infra.kuid.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          k:{"uid":"fe54f007-12a1-4a44-8d7a-5764db23732a"}: {}
      f:spec:
        f:endpoints: {}
        f:internal: {}
    manager: topo.kubenet.dev.topologies.nodelink
    operation: Apply
    time: "2024-09-08T13:21:36Z"
  - apiVersion: infra.kuid.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"IPClaimReady"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: infra.kuid.dev.links.link-internal-id
    operation: Apply
    time: "2024-09-08T13:21:37Z"
  - apiVersion: infra.kuid.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"InterfaceReady"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: infra.kuid.dev.links.link-internal-if-si
    operation: Apply
    time: "2024-09-08T13:21:37Z"
  name: kubenet.region1.us-east.node1.1.1.node2.1.1
  namespace: default
  ownerReferences:
  - apiVersion: topo.kubenet.dev/v1alpha1
    controller: true
    kind: Topology
    name: kubenet
    uid: fe54f007-12a1-4a44-8d7a-5764db23732a
  resourceVersion: "5"
  uid: 64d72a34-f000-4d99-8c1b-bef2cf7cf37b
spec:
  endpoints:
  - adaptor: sfp
    endpoint: 1
    module: 0
    node: node1
    partition: kubenet
    port: 1
    region: region1
    site: us-east
  - adaptor: sfp
    endpoint: 1
    module: 0
    node: node2
    partition: kubenet
    port: 1
    region: region1
    site: us-east
  internal: true
status:
  conditions:
  - lastTransitionTime: "2024-09-08T13:21:37Z"
    message: ""
    reason: Ready
    status: "True"
    type: IPClaimReady
  - lastTransitionTime: "2024-09-08T13:21:36Z"
    message: ""
    reason: Ready
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-09-08T13:21:37Z"
    message: ""
    reason: Ready
    status: "True"
    type: InterfaceReady
