apiVersion: device.network.kubenet.dev/v1alpha1
kind: RoutingPolicy
metadata:
  creationTimestamp: "2024-09-08T13:21:36Z"
  managedFields:
  - apiVersion: device.network.kubenet.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          k:{"uid":"7655f1b7-4c09-471f-b89b-f3f865f96cab"}: {}
      f:spec:
        f:defaultAction:
          f:result: {}
        f:name: {}
        f:node: {}
        f:partition: {}
        f:region: {}
        f:site: {}
    manager: infra.kuid.dev.nodes.routingpolicy
    operation: Apply
    time: "2024-09-08T13:21:36Z"
  name: kubenet.region1.us-east.node1.overlay
  namespace: default
  ownerReferences:
  - apiVersion: infra.kuid.dev/v1alpha1
    controller: true
    kind: Node
    name: kubenet.region1.us-east.node1
    uid: 7655f1b7-4c09-471f-b89b-f3f865f96cab
  resourceVersion: "0"
  uid: 513e78e4-766a-4de5-bd44-c6a8dc3dfcd9
spec:
  defaultAction:
    result: reject
  name: kubenet.region1.us-east.node1.overlay
  node: node1
  partition: kubenet
  region: region1
  site: us-east
