apiVersion: device.network.kubenet.dev/v1alpha1
kind: PrefixSet
metadata:
  creationTimestamp: "2024-09-08T13:21:36Z"
  managedFields:
  - apiVersion: device.network.kubenet.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          k:{"uid":"7655f1b7-4c09-471f-b89b-f3f865f96cab"}: {}
      f:spec:
        f:name: {}
        f:node: {}
        f:partition: {}
        f:prefixes:
          k:{"prefix":"10.0.0.0/16"}:
            .: {}
            f:maskLengthRange: {}
            f:prefix: {}
          k:{"prefix":"1000::/64"}:
            .: {}
            f:maskLengthRange: {}
            f:prefix: {}
        f:region: {}
        f:site: {}
    manager: infra.kuid.dev.nodes.routingpolicy
    operation: Apply
    time: "2024-09-08T13:21:36Z"
  name: kubenet.region1.us-east.node1.loopbackipv6
  namespace: default
  ownerReferences:
  - apiVersion: infra.kuid.dev/v1alpha1
    controller: true
    kind: Node
    name: kubenet.region1.us-east.node1
    uid: 7655f1b7-4c09-471f-b89b-f3f865f96cab
  resourceVersion: "0"
  uid: eca6e3bb-eb51-4651-8839-95d53172a592
spec:
  name: kubenet.region1.us-east.node1.loopbackipv6
  node: node1
  partition: kubenet
  prefixes:
  - maskLengthRange: 128..128
    prefix: 10.0.0.0/16
  - maskLengthRange: 128..128
    prefix: 1000::/64
  region: region1
  site: us-east
