apiVersion: device.network.kubenet.dev/v1alpha1
kind: SubInterface
metadata:
  creationTimestamp: "2024-09-08T13:21:37Z"
  managedFields:
  - apiVersion: device.network.kubenet.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"BFDReady"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: device.network.kubenet.dev.subinterfaces.bfd
    operation: Apply
    time: "2024-09-08T13:21:37Z"
  - apiVersion: device.network.kubenet.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"BGPNeighborReady"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: device.network.kubenet.dev.subinterfaces.ebgpneighbor
    operation: Apply
    time: "2024-09-08T13:21:37Z"
  - apiVersion: device.network.kubenet.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          k:{"uid":"7655f1b7-4c09-471f-b89b-f3f865f96cab"}: {}
      f:spec:
        f:endpoint: {}
        f:id: {}
        f:ipv4:
          f:addresses: {}
        f:ipv6:
          f:addresses: {}
        f:name: {}
        f:node: {}
        f:partition: {}
        f:port: {}
        f:region: {}
        f:site: {}
        f:type: {}
    manager: infra.kuid.dev.nodes.if-si-ni
    operation: Apply
    time: "2024-09-08T13:21:37Z"
  name: kubenet.region1.us-east.node1.0.0.system.0
  namespace: default
  ownerReferences:
  - apiVersion: infra.kuid.dev/v1alpha1
    controller: true
    kind: Node
    name: kubenet.region1.us-east.node1
    uid: 7655f1b7-4c09-471f-b89b-f3f865f96cab
  resourceVersion: "2"
  uid: e0fad48b-e642-476c-96e9-3831e269094c
spec:
  endpoint: 0
  id: 0
  ipv4:
    addresses:
    - 10.0.0.0/32
  ipv6:
    addresses:
    - 1000::/128
  name: system
  node: node1
  partition: kubenet
  port: 0
  region: region1
  site: us-east
  type: routed
status:
  conditions:
  - lastTransitionTime: "2024-09-08T13:21:37Z"
    message: ""
    reason: Ready
    status: "True"
    type: BFDReady
  - lastTransitionTime: "2024-09-08T13:21:37Z"
    message: ""
    reason: Ready
    status: "True"
    type: BGPNeighborReady
