apiVersion: device.network.kubenet.dev/v1alpha1
kind: BGPDynamicNeighbor
metadata:
  creationTimestamp: "2024-09-08T13:21:37Z"
  managedFields:
  - apiVersion: device.network.kubenet.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"Ready"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: device.network.kubenet.dev.bgpdynamicneighbors.bgpdynamicneighbor
    operation: Apply
    time: "2024-09-08T13:21:37Z"
  - apiVersion: device.network.kubenet.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          k:{"uid":"ecf6be81-c341-4f99-8662-af87724203fe"}: {}
      f:spec:
        f:node: {}
        f:partition: {}
        f:region: {}
        f:site: {}
    manager: infra.kuid.dev.nodes.bgp
    operation: Apply
    time: "2024-09-08T13:21:37Z"
  name: kubenet.region1.us-east.node2
  namespace: default
  ownerReferences:
  - apiVersion: infra.kuid.dev/v1alpha1
    controller: true
    kind: Node
    name: kubenet.region1.us-east.node2
    uid: ecf6be81-c341-4f99-8662-af87724203fe
  resourceVersion: "1"
  uid: 6242feb0-d304-4bbd-bf97-90ec0fafc1be
spec:
  node: node2
  partition: kubenet
  region: region1
  site: us-east
status:
  conditions:
  - lastTransitionTime: "2024-09-08T13:21:37Z"
    message: ""
    reason: Ready
    status: "True"
    type: Ready
